# Generated by Django 4.2 on 2023-04-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
