# Generated by Django 4.2 on 2023-04-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsection', '0002_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(max_length=255, upload_to='videos'),
        ),
    ]
