# Generated by Django 4.2 on 2023-04-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsection', '0003_alter_video_thumbnail_alter_video_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='video_file_original',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_1080p',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_480p',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_720p',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='videos'),
        ),
    ]
